[build]
    command = 'CI= npm run build'
    functions = 'netlify/functions'
    publish = 'build'

[functions]
directory = "/netlify/functions/" 

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "https://darkmeowproductions.com/works"
  to = "/works"
  status = 200

[[redirects]]
  from = "https://darkmeowproductions.com/posts"
  to = "/posts"
  status = 200

[[redirects]]
  from = "https://darkmeowproductions.com/tutorials"
  to = "/tutorials"
  status = 200
